name: MSBuild

on:
  push:
    branches:
      - dev/pipeline

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Target Frameworks
      run: |
        Write-Host "Starting to extract target frameworks..."
        $csprojFiles = Get-ChildItem -Path './*.csproj', '**/*.csproj'
        Write-Host "Found .csproj files: $($csprojFiles.Count)"
        $frameworks = @()
        foreach ($file in $csprojFiles) {
            Write-Host "Processing file: $($file.FullName)"
            [xml]$csproj = Get-Content -Path $file.FullName
            $framework = $csproj.Project.PropertyGroup.TargetFramework
            Write-Host "Extracted framework: $framework"
            $frameworks += $framework
        }
        $uniqueFrameworks = $frameworks | Sort-Object -Unique
        Write-Host "Unique frameworks: $($uniqueFrameworks -join ',')"
        $uniqueFrameworks -join ',' | Out-File -FilePath frameworks.txt
        Write-Host "Content of frameworks.txt:"
        Get-Content frameworks.txt
        echo "frameworks=$(Get-Content frameworks.txt)" >> $GITHUB_ENV

    - name: Setup .NET
      run: |
        $frameworks = $env:frameworks -split ','
        foreach ($framework in $frameworks) {
          if ($framework -match 'net(\d+\.\d+)') {
            $version = $matches[1]
            echo "Installing .NET $version"
            actions/setup-dotnet@v1 --dotnet-version $version
          }
        }


    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: msbuild -t:Restore -p:Configuration=${{ matrix.configuration }}

    - name: Build solution
      run: msbuild -p:Configuration=${{ matrix.configuration }} -p:Platform=${{ matrix.platform }}

    - name: Create MSIX package
      run: msbuild -t:Pack -p:Configuration=${{ matrix.configuration }} -p:Platform=${{ matrix.platform }} -p:GenerateAppxPackageOnBuild=true

    - name: Upload MSIX package
      uses: actions/upload-artifact@v2
      with:
        name: msix-package
        path: '**/*.msix'
